### ISSUE TITLE
DefiSafe Protocol

### ISSUE THREAD

**Issue by Jack-Zhang01** [SecretFoundation/Grants#1]
Team Name: DefiSafe Protocol Team

Project Description

This is an **DefiSafe Protocol** application for a grant programme: **Secret Network Grant Program: Secret Apps**

We intend to create an insurance product on Secret Network, which will enable Secret Network users to obtain a certain amount of compensation if the price drops when holding SNIP-20 tokens. Last year, our team has been paying attention to Ethereum Defi and has been building the Defisafe protocol. Version 1.0 has been launched on the Ethereum mainnet. The community has reported that the economic model is unreasonable, so version 1.0 has been discontinued, and version 2.0 has now been deployed on Ethereum. kovan testnet. At present, due to the high cost of Ethereum gas, we are always looking for other suitable ecosystems. Recently, we noticed Secret Network and frequently interacted with Secret Network on Twitter. Needless to say, we are very happy to see the development of this project and hope to participate in it and get support from Secret Network.

## Problem / Solution
In terms of investment, profit & loss have become an unavoidable problem. Especially in the field of digital currency, the 24h x 365d transaction and unlimited transaction patterns not only bring huge returns to the purchasers, but also produce huge risks of loss.

Our priority is given to how to provide the investors with better guarantee when designing our products. At present, some decentralized insurance products are available on the market, but some shortcomings still exist. Most products are suitable for minor probability events such as hackers and vulnerabilities. The process of filing claims is more complicated, and voting and other processes are required, so it is likely that the insured users which have incurred losses cannot obtain timely compensation. Compared with minor probability events such as hackers and vulnerabilities, DefiSafe chose a situation that investors are more likely to encounter: losses. Through DefiSafe, users who hold encrypted assets can not only enjoy the appreciation in asset arising from price rise, but also take lower risks of price fall of the encrypted assets.

## Detailed product description
Defisafe establishes a pool of venture capital based on smart contract, so that users can enjoy the appreciation brought by price rise and share the risk of asset shrinkage when the price falls. It can be understood as a dynamic economic game model, that is, the game between smart contract and market. The contract involves many possibilities. As long as there is a possibility, that is, the victory of the contract, If the user's assets decrease, compensation can be obtained.
example:
userA holds secret-ETH
userB holds secret-KNC
userC holds secret-BTC
If one of the three users makes a profit, part of the profit will go into the venture capital pool, the loss users will get the secret-DSE compensation, and the funds in the venture capital pool will buy secret-DSE through secretswap.

## Go-to-Market plan
The secret network is developing rapidly. We hope to participate in it and get the support of the secret network.

## Team members
* Jack
* Sundy
* Kater
* Chris Powers
* Tao
* Globalbst

## Team Website	
* http://defisafe.net/v2

## Team's experience
* Jack
DefiSafe founder, full stack development engineer, senior developer, has ten years of development experience, worked as an Apple development engineer, participated in a number of block chain projects, formed a team to participate in the global hacker competition, in early 2019, began to deepen Defi research and development, in mid-2019 began to form a team to create DefiSafe project.
* Sundy
DefiSafe front-end development engineer, senior front-end development engineer, good at front-end field development, technology stack for java, python front-end React Angular and other popular frameworks. Has rich front-end development experience, independently developed a number of open source projects, block chain project senior player, currently mainly invested in the field of block chain project development.
* Kater
DefiSafe UI designer, senior UI designer in the software testing industry, with many years of working experience, project leader of the corporate image design department of Anban, co-founder of DefiSafe, responsible for the overall interface / interaction design of the start-up and revision of DefiSafe.
* Tao
DefiSafe smart contract engineer, full stack development engineer, focusing on research and development in the field of smart contracts, focusing on DeFi (decentralized finance) projects, publishing many industry research reports, successfully assisting a well-known capital to complete technical due diligence. He has provided data analysis for the Big Data Strategy Research Institute, participated in many projects such as Benchmark, Mao Yan System, Micro analysis System, etc., published works, and analyzed the regional agglomeration of new enterprises based on the Moran SI Index.
* Globalbst
DefiSafe Project Manager, Co-Founder of Community Operation Bit Future, Block chain Entrepreneur, Author of Enterprise Transformation and Uplink Guide- "Innovator, Enterprise Uplink Case Operation Guidance Manual," Participated in the scheme design and community operation of multiple projects, such as smart farm block chain trace ability, jade DeFi, real estate ownership pass mapping (STO), art uplink (NFT) solutions, etc., and have rich experience in transforming block chain business in traditional fields.
* Chris Powers | New York
DefiSafe product architect DefiSafe US partner, DxDAO partner, financial practitioner, focusing on decentralized finance and financial derivatives, designing a number of block chain financial products, and very in-depth research in the DAO field.

## Team Code Repos
https://github.com/defisafe

## Development Roadmap
We will require 4 months to complete this project.
The total cost we need is: $60000, which is mainly used for the following purposes: 1. Community promotion 2. Providing liquidity for secret-DSE in secretswap 3. Expenses of project personnel

Example milestones:
* Implement Community migration (weeks 0 - 4).
* Implement Development completed (weeks 4 - 12).
* Implement Test network phase (weeks 12 - 16).

## Additional Information
This is our demo video on Ethereum：https://youtu.be/qd6ULXGE5qc

**Comment by cankisagun** [comment]
Hey guys, thank you for the proposal. I tired to play with the app on Kovan but couldn't get it to work. A couple of points:

We primarily fund development work and we need more detailed roadmap, where you need to have milestones that are better detailed (more specific - i.e. I don't know what migration of community means) and measurable.

We'd also like to see a breakdown of costs for the proposed budget. My initial reaction is that $60K is on the higher end to justify the value add of to the ecosystem. Value capture for Secret Network ecosystem would be:
- The main KPIs for Secret Network is TVL (privacy value add to other blockchain ecosystems), 
- number of transactions
- number of user (for applications)
_you can feel free to create a forum post and try to engage whether Secret Network users would be interested in this product_

The ecosystem fund is not aimed to fund community promotion and /or liquidity in the product.

I hope you engage directly with the community and revise this submission if you see interest :) 

Good luck!

**Comment by cankisagun** [comment]
Not enough interest from the community. Closing the issue. @Jack-Zhang01 feel free to DM me on discord if you want to brainstorm ideas or want to work on a concept from our grant list
