### ISSUE TITLE
Educational Video Series for Secret Network by Finstreet

### ISSUE THREAD

**Issue by sahil-finstreet** [SecretFoundation/Grants#5]
# Finstreet

## Project Description
Finstreet is India’s First Crypto Education Institute. This platform acts as an easily accessible medium for people to learn about the importance of cryptocurrencies and the different asset classes associated with them.

We will create an educational video series educating people about Secret Network. This video series will focus on why privacy is important when it comes to finance and how Secret Network is solving this problem on a large scale.

## Problem / Solution

**Channels for distribution:**

[YouTube ](https://www.youtube.com/c/Finstreet) 33,000 subscribers

[Bolo Indya](https://www.boloindya.com/user/14906060/finstreet) 70,400 followers

[Trell](https://trell.co/@Finstreet) 65,000 followers

[MX Takatak](https://usr.mxtakatak.com/vQZT/2d9f74c2) 1,19,200 followers

[DailyHunt Josh](https://share.myjosh.in/profile/a1d3a003-0db0-41ed-abfc-fe28e6b76a7a) 2,91,100 followers

More than **500K** people in the crypto and blockchain interested community.

**Key Facts:**

- 500k+ followers
- 10 million-plus monthly views on all platforms
- 3.5 million impressions per month on YouTube
- Verified profiles on 6 platforms
- 100% organic traffic
- 40% month on month growth
- The educational content in Hindi and English
- Targeting niche Indian audience

**Video formats:**

- Daily Crypto News
- Review videos
- Interviews with leading industry experts
- Explainers
- Tutorial videos

## Detailed product description

Key deliverables:

- Bi-weekly news or update about Secret Network for the next three months 
- 6 explainer videos about the Secret network
- 3 specific interview videos featuring the core team members of the Secret network so that the world can share the vision of this project.

Key KPIs to be achieved with the campaign:

1 million views on content related to Secret Network.
5 million impressions of the entire campaign.

## Value capture for Secret Network ecosystem
The campaign will :

- Educate people about Secret Network and its use cases.
- Create better and relevant reach in India and other Hindi speaking nations.
- Create Brand awareness among the Indian crypto community.
- Detailed introduction of the project
- Help in creating strong brand recall value among the blockchain and crypto community.
- Regular updates about Secret to the Indian community.

## Team members
* Bandhul Bansal
* Sahil Thakur

## Team Website	
https://finstreet.in/

## Team's experience

1. Bandhul Bansal, CEO of Finstreet (E-mail:bandhul@finstreet.in)

Bandhul is an avid investor with experience of more than 7 years. Finstreet is the brainchild of Bandhul. He has been coaching and educating masses about the importance of financial freedom for the past 4 years and is a hardcore crypto believer. 

3. Sahil Thakur, Head of Partnerships (E-mail:associations@finstreet.in)

Sahil is a crypto enthusiast who has experience working with projects like Huobi, Deribit, Biconomy, Aave, FTX, Paxful, WazirX etc. 

## Team LinkedIn Profiles
* https://www.linkedin.com/in/bandhul-bansal-09b0a1114
* https://www.linkedin.com/in/sahil-thakur-351277160

## Development Roadmap
We will require 3 months to complete this campaign. We will release 1 bi-weekly news update and 6 dedicated videos about the Secret network along with 3 interviews.
 
We are looking for a grant of 6,000$. The payment schedule will be as followed:
1. At the time of grant approval- 3,000 USD
2. At the starting of the second month- 1,500 USD
3. At the starting of the third month- 1,500 USD

We would be willing to consider full payment in SCRTs.

**Comment by cankisagun** [comment]
@sahil-finstreet thanks for your submission. This is more suitable for a SNAC application, please check forum.scrt.network and awareness channel in discord to get feedback on this cc @torsecret

**Comment by cankisagun** [comment]
Need to apply as a SNAC
