### ISSUE TITLE
SecretStore - an eCommerce platform accepting SNIP20 tokens

### ISSUE THREAD

**Issue by cryptocurnc** [SecretFoundation/Grants#9]
# SecretStore – secretnetwork.store / sscrt.store

## Project Description

The goal is to create an online shopping cart that accepts Secret Network’s SNIP20 tokens as payment, providing merchants and customers with a way of using any cryptocurrency to do business in a private manner.

## Problem / Solution

There are numerous online shopping carts available that accept cryptocurrencies as a form of payment. Most cryptocurrencies are not private, which means all transactions between a store and its customers are visible to the public via the blockchain.

One solution to this is to use a cryptocurrency with privacy features, like Monero, and there are shopping carts available that support Monero. However, my proposed solution is a shopping cart that accepts Secret Network’s SNIP20 tokens, providing merchants and customers with a way of using ANY cryptocurrency in a private manner.

## Detailed product description

The idea is to create a JavaScript shopping cart and inventory management system that anyone can easily download, configure, and deploy on their own website. I want it to be simple enough for someone with limited blockchain experience to be able to set up.

A store owner will configure their inventory with product images, descriptions, and prices. Prices will be displayed in whichever SNIP20 token the store owner chooses. They will also enter the wallet address that they would like to receive funds at.

Customers will browse the inventory, add items that they want to the shopping cart, and then go through the check-out process. Here they will enter their shipping address, then continue to the payment. This is where the interaction with Secret Network will occur. The payment button will integrate with Keplr, opening a pop-up window with the total amount owed as a transaction between the customer’s wallet and the store wallet. The shopping cart will then take the customer’s wallet address, shipping address, and order total and send it to the backend database. The store owner will then receive a notification that an order has been placed. Before shipping, they can verify the transaction by checking to see if the store wallet received the correct amount from the customer’s wallet. 

## Go-to-Market plan

As phase one of this project, I will operate the first working version of the code as a Secret Network merch store. This will bring attention to the project and act as a beta test, providing valuable feedback and allowing me fix any bugs. I will sell things with the Secret Network logo on them, such as stickers, coffee mugs, and t-shirts. They will be sold for sSCRT, allowing community members to directly swap their SCRT tokens for merch.

After a month of beta testing, phase two will be to release the code in an easily configurable package, allowing anyone to set up their own store. The project website will be modified, acting not only as a Secret Network merch store, but also encouraging people to download and set up a store on their own website. The site will educate people on the benefits of using SNIP20 tokens for private transactions.

I will continue to operate my example of the code as a Secret Network merch store as long as I’m involved with the community, so for the foreseeable future.

## Value capture for Secret Network ecosystem

This project will promote the use of SNIP20 tokens and educate people on the benefits of using Secret Network for private transactions. For the first time ever, people will be able to swap Secret Network tokens directly for real-world items. If it gains popularity, it could spread the use of SNIP20 tokens to many different websites. Other Secret Network entities such as the Secret Foundation, committees, validators, community projects, and partner organizations could set up their own stores and offer items for SNIP20 tokens. NFTs and other virtual items could also be sold.

## Team members

Patrick, aka “Cryptocurnc”

An original investor in ENG, I found out about Secret Network in February, and have been very actively involved with the community since then. I’m a 30 year old male from the USA. I have an associate degree in Information Systems Security, and have 7 years of experience working in IT support and administration. I’ve been following the blockchain space casually since 2011, and seriously since 2017. Although I don’t have a lot of development experience, I’m familiar with modifying open source projects, and believe I have the knowledge to pull this off.

## Development Roadmap

The goal is for this to be complete within two months. I am requesting a total of 4000 SCRT for two months of part-time work. Ideally, payments would be disbursed at these key milestones:

Phase 0, May 1st – 400 SCRT: Begin developing the store
Phase 1, June 1st – 1800 SCRT: Launch the Secret Network Merch Store
Phase 2, July 1st – 1800 SCRT: Release the code for mass distribution

# Closing

Thank you for your time and consideration, I look forward to building something awesome!

**Comment by cankisagun** [comment]
@cryptocurnc can you please share this on the forum and get some feedback from the community. I specifically have 2 questions:
1) What's the current process of acquiring SCRT merch? I think just the idea of having an online SCRT merc. store that accepts snip20s would be cool.
2) WHat's your plan on on-boarding other merchants to the platform? Eventually we would like to move beyond just the SCRT merch. store

Would be great to get some community feedback on these ideas

**Comment by cryptocurnc** [comment]
Hey Can, will do! https://forum.scrt.network/t/grant-proposal-secretstore/3308 I replied to your questions there.
